[package]
authors = [ "arunxxxl <arunberry47@gmail.com>" ]
edition = "2018"
name    = "web"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb = "0.4.7"
